language: node_js

node_js:
  - "4"
  - "5"
  - "6"

install:
  - npm install

before_deploy:
  - npm run bundle

deploy:
  # deploy to github release
  - provider: releases
    skip_cleanup: true
    on:
      tags: true
    api_key:
      secure: "Es/wJFl/HMEQaaPVhPn/N9VqMIi6QkLBT7zJkOZX+H8lJvgbqegl7T9kyvaxCyLT420pI5asv1EkHEWTKChF+Wn9uU9Da//P8ToJ4WdR3yoSorAdS55k0+QXrOR8esvZ06OCsw4Qz3S//3nTcfX5p7ueO+StDiUQfPNnKQYZQdg3s2Vcvrxaya97auE2AJyDLPJMUNNwhzma3qdsX98wgjfRj81uH1Sob+U5AmlA+zOHklpWskzgdcheW/TdrbV/JjkPVqvdQmWOwYEJOJun+QSbXDAO5YATTcWE2kYguKcXTUJKuDJ+G+PtoypjcARG/sQTNpgADuuT/2O2nJDlNKctUMlTPtO3aegsaKG0PtAkPHh5Be+kA+pjCXPuEwyLdx0KzNWzTzLvg9P+wOtHYvo+XiHXVXM1F4MTrkTmoiiebWU7fVgfUqHZGDpNCEKqNI3HCDVZquN9Dvb/pu4NPjH3Z/C+RVoDVUad0Fn2hqqT8R2sAZpGl++cDPhah5XCYnpVpz3SG2z309QjJQmMK/zrL5OC63YSPjyn91bjnFk+w+2bs80sq+Xzxzx/akMuG6oPZCOKytC++Kw4xHX6pSqNt8pfoyEbHmISqpBSO2cHWCN5DmauN8GF8jzKeGZuVABJOypYaGA9BVPTT+PCIWsxQYw4cM6VVEuypA6/vSw="
    file:
        - "./dist/sinon-chrome.min.js"
        - "./dist/sinon-chrome-apps.min.js"
        - "./dist/sinon-chrome-webextensions.min.js"

